### ISSUE TITLE
Copy message from other channel

### ISSUE THREAD

**Issue by ashkufaraz** [Ardakilic/Telegram-bot-php#7]
Hi
Sorry,I have a question about your project(telegram).
Can I get the message channels that I'm not their admin?
I want write a script that read message from other chanel and write to
my chanel.
I can do it?
best regards
thanks

**Comment by Ardakilic** [comment]
Hello, as far as I know Telegram limits the bots. The bots cannot read other users's messages. Telegram Bots only reads the messages you send them to. So I don't think it's possible.

**Comment by Ardakilic** [comment]
This repository is deprecated in regards of the total rewrite:

https://github.com/Ardakilic/Telebot2/

Please follow that one. I'm sure you'll like it way better than this :+1: 

Closing this issue regarding the new one.
